[project]
name = "wagtail-ninja"
version = "0.1.4"
description = "Opinionated Ninja API for Wagtail"
requires-python = ">=3.12"
dependencies = [
    "django-ninja>=1.4.3",
    "orjson>=3.10.18",
]

[dependency-groups]
dev = [
    "icecream>=2.1.5",
    "ruff>=0.12.1",
    "wagtail>=7.0.1",
]
